//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shkodin.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int IdOrder { get; set; }
        public int IdSize { get; set; }
        public int IdRoom { get; set; }
        public int IdInterior { get; set; }
        public int IdType { get; set; }
        public string WishesOrder { get; set; }
        public int IdStaff { get; set; }
        public int IdColorSchemeOfTheHall { get; set; }
        public string Equipment { get; set; }
        public int IdEquipping { get; set; }
        public string AddonFromBuyer { get; set; }
    
        public virtual ColorSchemeOfTheHall ColorSchemeOfTheHall { get; set; }
        public virtual Equipping Equipping { get; set; }
        public virtual Interior Interior { get; set; }
        public virtual Room Room { get; set; }
        public virtual Size Size { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Type Type { get; set; }
    }
}
